import { PageContentData } from '@/lib/types';

export const content: PageContentData = {
  key: "in-house-training-k3-kendal",
  updated: "2026-08-29",
  faq: [
  {
    "q": "Apakah laporan pasca pelatihan dapat diterbitkan dalam Bahasa Inggris?",
    "a": "Ya, kami menyediakan Executive Summary Report dan transkrip evaluasi peserta dalam Bahasa Inggris."
  }
],
  html: "<p>Kawasan Ekonomi Khusus Kendal (KIK Park by the Bay) berkembang pesat dengan puluhan tenant PMA dari Singapura, Jepang, Tiongkok, dan Eropa.</p>\n\n<h2 id=\"identifikasi-bahaya\">Identifikasi Bahaya Kritis &amp; Manajemen Risiko Operasional</h2>\n<p>Kegagalan dalam mematuhi prosedur operasi standar pada program ini memicu dampak fatalitas tinggi, kerusakan aset mekanikal masif, serta tuntutan hukum atas kelalaian keselamatan kerja. Beberapa potensi bahaya kritis meliputi:</p>\n<ul class=\"check-list\">\n  <li>Interaksi mesin otomatis presisi, sistem kelistrikan tegangan tinggi, dan material handling.</li>\n</ul>\n\n<h2 id=\"landasan-hukum\">Kerangka Hukum &amp; Standar Regulasi Ketenagakerjaan</h2>\n<p>Pelatihan ini disusun mengacu pada hierarki regulasi nasional dan standar industri internasional yang berlaku di Indonesia:</p>\n<ul>\n  <li>PP No. 50 Tahun 2012.</li>\n</ul>\n\n<h2 id=\"silabus-komprehensif\">Struktur Kurikulum &amp; Silabus Teknis Lengkap</h2>\n<div class=\"table-scroll\"><table>\n  <tr><th>Modul Pelatihan</th><th>Cakupan Materi Teori &amp; Analisis</th><th>Simulasi Praktik &amp; Workshop</th></tr>\n  <tr><td><strong>Modul 1: Global Safety Compliance KEK Kendal</strong></td><td>SMK3, ISO 45001, Machine Guarding.</td><td>Audit kelaikan mesin pabrik.</td></tr>\n</table></div>\n\n<h2 id=\"matriks-teknis\">Matriks Spesifikasi Teknis &amp; Standar Verifikasi Lapangan</h2>\n<div class=\"table-scroll\"><table>\n  <tr><th>Zona KEK Kendal</th><th>Program Pilihan</th></tr>\n  <tr><td>Kendal Industrial Park</td><td>Ahli K3 Umum, LOTO, SIO Forklift, ISO 45001</td></tr>\n</table></div>\n<h2 id=\"fasilitas-praktik\">Peralatan, Tooling &amp; Sarana Uji Praktik Lapangan</h2>\n<p>Peserta pelatihan dibekali pengalaman langsung mengoperasikan instrumen dan alat keselamatan berstandar industri bersertifikasi:</p>\n<ul class=\"check-list\">\n  <li>Digital Safety Sensor Tester.</li>\n</ul>\n\n<h2 id=\"sasaran-peserta\">Profil Sasaran Peserta Pelatihan</h2>\n<p>Program in-house dan sertifikasi ini dirancang bagi tenaga profesional perusahaan:</p>\n<ul>\n  <li>Expat Plant Lead, Indonesian Safety Officer, dan HR Kendal.</li>\n</ul>\n\n<h2 id=\"metodologi-evaluasi\">Metodologi Evaluasi &amp; Uji Kompetensi Kelulusan</h2>\n<p>Penilaian kelulusan peserta dilakukan secara objektif melalui ujian teori tertulis (Pre-Test &amp; Post-Test) dengan batas kelulusan minimal, observasi langsung pada uji praktik lapangan, serta verifikasi portofolio kerja. Peserta yang dinyatakan kompeten akan memperoleh Sertifikat Resmi Kualifikasi K3.</p>\n\n<h2 id=\"program-terkait\">Navigasi Program Terkait &amp; Lanjutan</h2>\n<p>Perkuat integrasi sistem keselamatan dan produktivitas tim operasional fasilitas Anda melalui program pilihan:</p>\n<p>\n  <a href=\"/jenis-pelatihan/in-house-training-k3-semarang/\">In-House Training Semarang</a>\n</p>"
};
