import { PageContentData } from '@/lib/types';

export const content: PageContentData = {
  key: "in-house-training-k3-medan",
  updated: "2026-08-29",
  faq: [
  {
    "q": "Apakah kami bisa meminta jadwal pelatihan di hari Sabtu/Minggu?",
    "a": "Ya, jadwal in-house training dapat diatur pada akhir pekan tanpa mengganggu hari kerja produksi."
  }
],
  html: "<p>Medan dan Kawasan Industri Medan (KIM) merupakan pusat pengolahan minyak kelapa sawit (CPO), industri karet, dan logistik ekspor pelabuhan Belawan Sumatera Utara.</p>\n\n<h2 id=\"identifikasi-bahaya\">Identifikasi Bahaya Kritis &amp; Manajemen Risiko Operasional</h2>\n<p>Kegagalan dalam mematuhi prosedur operasi standar pada program ini memicu dampak fatalitas tinggi, kerusakan aset mekanikal masif, serta tuntutan hukum atas kelalaian keselamatan kerja. Beberapa potensi bahaya kritis meliputi:</p>\n<ul class=\"check-list\">\n  <li>Risiko uap boiler PKS, ledakan debu cangkang sawit, dan lalu lintas forklift depo.</li>\n</ul>\n\n<h2 id=\"landasan-hukum\">Kerangka Hukum &amp; Standar Regulasi Ketenagakerjaan</h2>\n<p>Pelatihan ini disusun mengacu pada hierarki regulasi nasional dan standar industri internasional yang berlaku di Indonesia:</p>\n<ul>\n  <li>UU Uap 1930.</li>\n  <li>Permenaker No. 8/2020.</li>\n</ul>\n\n<h2 id=\"silabus-komprehensif\">Struktur Kurikulum &amp; Silabus Teknis Lengkap</h2>\n<div class=\"table-scroll\"><table>\n  <tr><th>Modul Pelatihan</th><th>Cakupan Materi Teori &amp; Analisis</th><th>Simulasi Praktik &amp; Workshop</th></tr>\n  <tr><td><strong>Modul 1: K3 Industri Pengolahan Sawit & Oleokimia Sumut</strong></td><td>Boiler, Sterilizer, Bejana Tekan.</td><td>Audit bejana uap di pabrik.</td></tr>\n</table></div>\n\n<h2 id=\"matriks-teknis\">Matriks Spesifikasi Teknis &amp; Standar Verifikasi Lapangan</h2>\n<div class=\"table-scroll\"><table>\n  <tr><th>Kawasan Medan</th><th>Program Unggulan</th></tr>\n  <tr><td>KIM 1-5 Mabar & Belawan</td><td>Operator Boiler, Ahli K3 Umum, SIO Forklift</td></tr>\n</table></div>\n<h2 id=\"fasilitas-praktik\">Peralatan, Tooling &amp; Sarana Uji Praktik Lapangan</h2>\n<p>Peserta pelatihan dibekali pengalaman langsung mengoperasikan instrumen dan alat keselamatan berstandar industri bersertifikasi:</p>\n<ul class=\"check-list\">\n  <li>Boiler Safety Valve Tester & Sound Meter.</li>\n</ul>\n\n<h2 id=\"sasaran-peserta\">Profil Sasaran Peserta Pelatihan</h2>\n<p>Program in-house dan sertifikasi ini dirancang bagi tenaga profesional perusahaan:</p>\n<ul>\n  <li>Mill Manager PKS Sumut, HSE Officer KIM, dan Maintenance Lead.</li>\n</ul>\n\n<h2 id=\"metodologi-evaluasi\">Metodologi Evaluasi &amp; Uji Kompetensi Kelulusan</h2>\n<p>Penilaian kelulusan peserta dilakukan secara objektif melalui ujian teori tertulis (Pre-Test &amp; Post-Test) dengan batas kelulusan minimal, observasi langsung pada uji praktik lapangan, serta verifikasi portofolio kerja. Peserta yang dinyatakan kompeten akan memperoleh Sertifikat Resmi Kualifikasi K3.</p>\n\n<h2 id=\"program-terkait\">Navigasi Program Terkait &amp; Lanjutan</h2>\n<p>Perkuat integrasi sistem keselamatan dan produktivitas tim operasional fasilitas Anda melalui program pilihan:</p>\n<p>\n  <a href=\"/industri/perkebunan-dan-pabrik-kelapa-sawit/\">K3 Pabrik Sawit</a>\n</p>"
};
