import { PageContentData } from '@/lib/types';

export const content: PageContentData = {
  key: "in-house-training-k3-makassar",
  updated: "2026-08-29",
  faq: [
  {
    "q": "Berapa hari durasi pelaksanaan in-house Ahli K3 Umum di Makassar?",
    "a": "Pelatihan Ahli K3 Umum Kemnaker RI berdurasi 12 hari kerja intensif termasuk ujian komprehensif."
  }
],
  html: "<p>Makassar adalah pintu gerbang logistik dan industri utama di Indonesia Timur dengan pelabuhan Makassar New Port dan kawasan industri KIMA.</p>\n\n<h2 id=\"identifikasi-bahaya\">Identifikasi Bahaya Kritis &amp; Manajemen Risiko Operasional</h2>\n<p>Kegagalan dalam mematuhi prosedur operasi standar pada program ini memicu dampak fatalitas tinggi, kerusakan aset mekanikal masif, serta tuntutan hukum atas kelalaian keselamatan kerja. Beberapa potensi bahaya kritis meliputi:</p>\n<ul class=\"check-list\">\n  <li>Operasi crane peti kemas pelabuhan, kelaikan listrik industri, dan mesin pabrik semen.</li>\n</ul>\n\n<h2 id=\"landasan-hukum\">Kerangka Hukum &amp; Standar Regulasi Ketenagakerjaan</h2>\n<p>Pelatihan ini disusun mengacu pada hierarki regulasi nasional dan standar industri internasional yang berlaku di Indonesia:</p>\n<ul>\n  <li>UU No. 1 Tahun 1970.</li>\n</ul>\n\n<h2 id=\"silabus-komprehensif\">Struktur Kurikulum &amp; Silabus Teknis Lengkap</h2>\n<div class=\"table-scroll\"><table>\n  <tr><th>Modul Pelatihan</th><th>Cakupan Materi Teori &amp; Analisis</th><th>Simulasi Praktik &amp; Workshop</th></tr>\n  <tr><td><strong>Modul 1: K3 Kepelabuhanan & Manufaktur Indonesia Timur</strong></td><td>Port Safety, SMK3, K3 Listrik.</td><td>Inspeksi fisik alat keselamatan.</td></tr>\n</table></div>\n\n<h2 id=\"matriks-teknis\">Matriks Spesifikasi Teknis &amp; Standar Verifikasi Lapangan</h2>\n<div class=\"table-scroll\"><table>\n  <tr><th>Kawasan Makassar</th><th>Program Unggulan</th></tr>\n  <tr><td>KIMA Daya & New Port</td><td>Ahli K3 Umum, K3 Maritim, Forklift SIO</td></tr>\n</table></div>\n<h2 id=\"fasilitas-praktik\">Peralatan, Tooling &amp; Sarana Uji Praktik Lapangan</h2>\n<p>Peserta pelatihan dibekali pengalaman langsung mengoperasikan instrumen dan alat keselamatan berstandar industri bersertifikasi:</p>\n<ul class=\"check-list\">\n  <li>Insulation Tester & Port Safety Harness.</li>\n</ul>\n\n<h2 id=\"sasaran-peserta\">Profil Sasaran Peserta Pelatihan</h2>\n<p>Program in-house dan sertifikasi ini dirancang bagi tenaga profesional perusahaan:</p>\n<ul>\n  <li>HSE Coordinator KIMA, Terminal Port Lead, dan Praktisi K3 Sulawesi.</li>\n</ul>\n\n<h2 id=\"metodologi-evaluasi\">Metodologi Evaluasi &amp; Uji Kompetensi Kelulusan</h2>\n<p>Penilaian kelulusan peserta dilakukan secara objektif melalui ujian teori tertulis (Pre-Test &amp; Post-Test) dengan batas kelulusan minimal, observasi langsung pada uji praktik lapangan, serta verifikasi portofolio kerja. Peserta yang dinyatakan kompeten akan memperoleh Sertifikat Resmi Kualifikasi K3.</p>\n\n<h2 id=\"program-terkait\">Navigasi Program Terkait &amp; Lanjutan</h2>\n<p>Perkuat integrasi sistem keselamatan dan produktivitas tim operasional fasilitas Anda melalui program pilihan:</p>\n<p>\n  <a href=\"/kategori-pelatihan/ahli-k3-umum/\">Pelatihan Ahli K3 Umum</a>\n</p>"
};
