import { PageContentData } from '@/lib/types';

export const content: PageContentData = {
  key: "in-house-training-k3-bontang",
  updated: "2026-08-29",
  faq: [
  {
    "q": "Apakah materi mencakup bahaya suhu sangat rendah (Kriogenik)?",
    "a": "Ya, modul mencakup keselamatan fluida kriogenik LNG, pemuaian gas mendadak, dan APD khusus anti-frostbite."
  }
],
  html: "<p>Bontang adalah kota industri energi dan kimia kelas dunia di pesisir Kaltim dengan kilang pencairan gas alam (Badak LNG) dan produsen pupuk urea terbesar (Pupuk Kaltim).</p>\n\n<h2 id=\"identifikasi-bahaya\">Identifikasi Bahaya Kritis &amp; Manajemen Risiko Operasional</h2>\n<p>Kegagalan dalam mematuhi prosedur operasi standar pada program ini memicu dampak fatalitas tinggi, kerusakan aset mekanikal masif, serta tuntutan hukum atas kelalaian keselamatan kerja. Beberapa potensi bahaya kritis meliputi:</p>\n<ul class=\"check-list\">\n  <li>Gas kriogenik LNG bersuhu -162°C dan tangki penyimpanan gas amonia berkapasitas puluhan ribu ton.</li>\n</ul>\n\n<h2 id=\"landasan-hukum\">Kerangka Hukum &amp; Standar Regulasi Ketenagakerjaan</h2>\n<p>Pelatihan ini disusun mengacu pada hierarki regulasi nasional dan standar industri internasional yang berlaku di Indonesia:</p>\n<ul>\n  <li>PP No. 11/1979.</li>\n  <li>Kepmenaker No. 187/1999.</li>\n</ul>\n\n<h2 id=\"silabus-komprehensif\">Struktur Kurikulum &amp; Silabus Teknis Lengkap</h2>\n<div class=\"table-scroll\"><table>\n  <tr><th>Modul Pelatihan</th><th>Cakupan Materi Teori &amp; Analisis</th><th>Simulasi Praktik &amp; Workshop</th></tr>\n  <tr><td><strong>Modul 1: Cryogenic & Petrochemical Safety Bontang</strong></td><td>Cryogenic burns, Boiling Liquid Expanding Vapor Explosion (BLEVE), PSM.</td><td>Drill tanggap darurat amonia.</td></tr>\n</table></div>\n\n<h2 id=\"matriks-teknis\">Matriks Spesifikasi Teknis &amp; Standar Verifikasi Lapangan</h2>\n<div class=\"table-scroll\"><table>\n  <tr><th>Kawasan Bontang</th><th>Fokus Pelatihan</th></tr>\n  <tr><td>Pupuk Kaltim & Badak LNG</td><td>Ahli K3 Kimia, CSMS, Bejana Tekan, LOTO</td></tr>\n</table></div>\n<h2 id=\"fasilitas-praktik\">Peralatan, Tooling &amp; Sarana Uji Praktik Lapangan</h2>\n<p>Peserta pelatihan dibekali pengalaman langsung mengoperasikan instrumen dan alat keselamatan berstandar industri bersertifikasi:</p>\n<ul class=\"check-list\">\n  <li>Cryogenic Safety Gloves & Ammonia Hazmat Suit.</li>\n</ul>\n\n<h2 id=\"sasaran-peserta\">Profil Sasaran Peserta Pelatihan</h2>\n<p>Program in-house dan sertifikasi ini dirancang bagi tenaga profesional perusahaan:</p>\n<ul>\n  <li>Process Engineer LNG, Operator Pabrik Pupuk, dan Vendor Rekanan Bontang.</li>\n</ul>\n\n<h2 id=\"metodologi-evaluasi\">Metodologi Evaluasi &amp; Uji Kompetensi Kelulusan</h2>\n<p>Penilaian kelulusan peserta dilakukan secara objektif melalui ujian teori tertulis (Pre-Test &amp; Post-Test) dengan batas kelulusan minimal, observasi langsung pada uji praktik lapangan, serta verifikasi portofolio kerja. Peserta yang dinyatakan kompeten akan memperoleh Sertifikat Resmi Kualifikasi K3.</p>\n\n<h2 id=\"program-terkait\">Navigasi Program Terkait &amp; Lanjutan</h2>\n<p>Perkuat integrasi sistem keselamatan dan produktivitas tim operasional fasilitas Anda melalui program pilihan:</p>\n<p>\n  <a href=\"/industri/petrokimia-dan-pupuk/\">K3 Petrokimia</a>\n</p>"
};
