import { PageContentData } from '@/lib/types';

export const content: PageContentData = {
  key: "in-house-training-k3-gresik",
  updated: "2026-08-29",
  faq: [
  {
    "q": "Apakah program in-house mencakup sertifikasi SIO Kemnaker resmi?",
    "a": "Ya, seluruh peserta yang lulus ujian teori dan praktik akan menerima sertifikat dan SIO resmi Kemnaker RI."
  }
],
  html: "<p>Kawasan Industri Gresik dan Java Integrated Industrial and Port Estate (JIIPE) menjadi pusat investasi kimia, pupuk, dan smelter tembaga skala dunia di Jawa Timur.</p>\n\n<h2 id=\"identifikasi-bahaya\">Identifikasi Bahaya Kritis &amp; Manajemen Risiko Operasional</h2>\n<p>Kegagalan dalam mematuhi prosedur operasi standar pada program ini memicu dampak fatalitas tinggi, kerusakan aset mekanikal masif, serta tuntutan hukum atas kelalaian keselamatan kerja. Beberapa potensi bahaya kritis meliputi:</p>\n<ul class=\"check-list\">\n  <li>Pelepasan gas kimia amonia, asam fosfat, dan keselamatan dermaga curah cair.</li>\n</ul>\n\n<h2 id=\"landasan-hukum\">Kerangka Hukum &amp; Standar Regulasi Ketenagakerjaan</h2>\n<p>Pelatihan ini disusun mengacu pada hierarki regulasi nasional dan standar industri internasional yang berlaku di Indonesia:</p>\n<ul>\n  <li>Kepmenaker No. 187/1999.</li>\n</ul>\n\n<h2 id=\"silabus-komprehensif\">Struktur Kurikulum &amp; Silabus Teknis Lengkap</h2>\n<div class=\"table-scroll\"><table>\n  <tr><th>Modul Pelatihan</th><th>Cakupan Materi Teori &amp; Analisis</th><th>Simulasi Praktik &amp; Workshop</th></tr>\n  <tr><td><strong>Modul 1: K3 Petrokimia & JIIPE Port Safety</strong></td><td>Chemical handling, PSM, Stevedoring.</td><td>Simulasi tanggap darurat amonia.</td></tr>\n</table></div>\n\n<h2 id=\"matriks-teknis\">Matriks Spesifikasi Teknis &amp; Standar Verifikasi Lapangan</h2>\n<div class=\"table-scroll\"><table>\n  <tr><th>Zona Industri Gresik</th><th>Program Terpopuler</th></tr>\n  <tr><td>JIIPE Manyar & KIG</td><td>Ahli K3 Kimia, SIO Forklift/Crane, Confined Space</td></tr>\n</table></div>\n<h2 id=\"fasilitas-praktik\">Peralatan, Tooling &amp; Sarana Uji Praktik Lapangan</h2>\n<p>Peserta pelatihan dibekali pengalaman langsung mengoperasikan instrumen dan alat keselamatan berstandar industri bersertifikasi:</p>\n<ul class=\"check-list\">\n  <li>Hazmat Chemical Suit & Ammonia Detector.</li>\n</ul>\n\n<h2 id=\"sasaran-peserta\">Profil Sasaran Peserta Pelatihan</h2>\n<p>Program in-house dan sertifikasi ini dirancang bagi tenaga profesional perusahaan:</p>\n<ul>\n  <li>HSE Petrokimia, Teknisi Pabrik Semen/Pupuk, dan Port Lead JIIPE.</li>\n</ul>\n\n<h2 id=\"metodologi-evaluasi\">Metodologi Evaluasi &amp; Uji Kompetensi Kelulusan</h2>\n<p>Penilaian kelulusan peserta dilakukan secara objektif melalui ujian teori tertulis (Pre-Test &amp; Post-Test) dengan batas kelulusan minimal, observasi langsung pada uji praktik lapangan, serta verifikasi portofolio kerja. Peserta yang dinyatakan kompeten akan memperoleh Sertifikat Resmi Kualifikasi K3.</p>\n\n<h2 id=\"program-terkait\">Navigasi Program Terkait &amp; Lanjutan</h2>\n<p>Perkuat integrasi sistem keselamatan dan produktivitas tim operasional fasilitas Anda melalui program pilihan:</p>\n<p>\n  <a href=\"/jenis-pelatihan/in-house-training-k3-surabaya/\">In-House Training Surabaya</a>\n</p>"
};
