import { PageContentData } from '@/lib/types';

export const content: PageContentData = {
  key: "in-house-training-k3-pasuruan",
  updated: "2026-08-29",
  faq: [
  {
    "q": "Apakah pelatihan P3K di Pasuruan menyertakan lisensi resmi Kemnaker?",
    "a": "Ya, lisensi Petugas P3K Kemnaker RI diterbitkan lengkap dengan buku panduan P3K resmi."
  }
],
  html: "<p>Kawasan Industri PIER Pasuruan menampung puluhan pabrik makanan-minuman multinasional, industri kemasan gelas, dan kimia hilir yang membutuhkan kepatuhan K3 prima.</p>\n\n<h2 id=\"identifikasi-bahaya\">Identifikasi Bahaya Kritis &amp; Manajemen Risiko Operasional</h2>\n<p>Kegagalan dalam mematuhi prosedur operasi standar pada program ini memicu dampak fatalitas tinggi, kerusakan aset mekanikal masif, serta tuntutan hukum atas kelalaian keselamatan kerja. Beberapa potensi bahaya kritis meliputi:</p>\n<ul class=\"check-list\">\n  <li>Bahaya uap boiler, refrigerasi amonia pabrik F&B, dan mesin pengemas.</li>\n</ul>\n\n<h2 id=\"landasan-hukum\">Kerangka Hukum &amp; Standar Regulasi Ketenagakerjaan</h2>\n<p>Pelatihan ini disusun mengacu pada hierarki regulasi nasional dan standar industri internasional yang berlaku di Indonesia:</p>\n<ul>\n  <li>Permenaker No. 05/2018.</li>\n</ul>\n\n<h2 id=\"silabus-komprehensif\">Struktur Kurikulum &amp; Silabus Teknis Lengkap</h2>\n<div class=\"table-scroll\"><table>\n  <tr><th>Modul Pelatihan</th><th>Cakupan Materi Teori &amp; Analisis</th><th>Simulasi Praktik &amp; Workshop</th></tr>\n  <tr><td><strong>Modul 1: Keselamatan Manufaktur F&B PIER</strong></td><td>Ergonomi, APAR, P3K, Boiler.</td><td>Praktik P3K dan pemadaman api.</td></tr>\n</table></div>\n\n<h2 id=\"matriks-teknis\">Matriks Spesifikasi Teknis &amp; Standar Verifikasi Lapangan</h2>\n<div class=\"table-scroll\"><table>\n  <tr><th>Kawasan Pasuruan</th><th>Spesialisasi</th></tr>\n  <tr><td>PIER Rembang & Beji</td><td>Petugas P3K, Operator Boiler, Ergonomi</td></tr>\n</table></div>\n<h2 id=\"fasilitas-praktik\">Peralatan, Tooling &amp; Sarana Uji Praktik Lapangan</h2>\n<p>Peserta pelatihan dibekali pengalaman langsung mengoperasikan instrumen dan alat keselamatan berstandar industri bersertifikasi:</p>\n<ul class=\"check-list\">\n  <li>CPR Mannequin & LOTO Kit.</li>\n</ul>\n\n<h2 id=\"sasaran-peserta\">Profil Sasaran Peserta Pelatihan</h2>\n<p>Program in-house dan sertifikasi ini dirancang bagi tenaga profesional perusahaan:</p>\n<ul>\n  <li>Factory Manager Pasuruan, HRD PIER, dan Tim K3.</li>\n</ul>\n\n<h2 id=\"metodologi-evaluasi\">Metodologi Evaluasi &amp; Uji Kompetensi Kelulusan</h2>\n<p>Penilaian kelulusan peserta dilakukan secara objektif melalui ujian teori tertulis (Pre-Test &amp; Post-Test) dengan batas kelulusan minimal, observasi langsung pada uji praktik lapangan, serta verifikasi portofolio kerja. Peserta yang dinyatakan kompeten akan memperoleh Sertifikat Resmi Kualifikasi K3.</p>\n\n<h2 id=\"program-terkait\">Navigasi Program Terkait &amp; Lanjutan</h2>\n<p>Perkuat integrasi sistem keselamatan dan produktivitas tim operasional fasilitas Anda melalui program pilihan:</p>\n<p>\n  <a href=\"/jenis-pelatihan/in-house-training-k3-surabaya/\">In-House Training Surabaya</a>\n</p>"
};
