import { PageContentData } from '@/lib/types';

export const content: PageContentData = {
  key: "in-house-training-k3-sorowako",
  updated: "2026-08-29",
  faq: [
  {
    "q": "Berapa hari durasi sertifikasi POP di Sorowako?",
    "a": "Pelatihan dan uji kompetensi POP BNSP berdurasi 6 hari kerja intensif."
  }
],
  html: "<p>Sorowako di Luwu Timur Sulawesi Selatan merupakan kawasan operasi penambangan nikel terintegrasi dengan teknologi pyrometallurgy dan tiga unit bendungan PLTA swasta.</p>\n\n<h2 id=\"identifikasi-bahaya\">Identifikasi Bahaya Kritis &amp; Manajemen Risiko Operasional</h2>\n<p>Kegagalan dalam mematuhi prosedur operasi standar pada program ini memicu dampak fatalitas tinggi, kerusakan aset mekanikal masif, serta tuntutan hukum atas kelalaian keselamatan kerja. Beberapa potensi bahaya kritis meliputi:</p>\n<ul class=\"check-list\">\n  <li>Lereng galian nikel laterit basah yang licin, pengoperasian hauler raksasa, dan turbin PLTA.</li>\n</ul>\n\n<h2 id=\"landasan-hukum\">Kerangka Hukum &amp; Standar Regulasi Ketenagakerjaan</h2>\n<p>Pelatihan ini disusun mengacu pada hierarki regulasi nasional dan standar industri internasional yang berlaku di Indonesia:</p>\n<ul>\n  <li>Kepmen ESDM No. 1827/2018.</li>\n</ul>\n\n<h2 id=\"silabus-komprehensif\">Struktur Kurikulum &amp; Silabus Teknis Lengkap</h2>\n<div class=\"table-scroll\"><table>\n  <tr><th>Modul Pelatihan</th><th>Cakupan Materi Teori &amp; Analisis</th><th>Simulasi Praktik &amp; Workshop</th></tr>\n  <tr><td><strong>Modul 1: K3 Tambang Nikel Laterit & Hydropower Sorowako</strong></td><td>Fatigue, Tanggul pengaman, Hydro turbine LOTO.</td><td>Audit jalan hauling licin saat hujan.</td></tr>\n</table></div>\n\n<h2 id=\"matriks-teknis\">Matriks Spesifikasi Teknis &amp; Standar Verifikasi Lapangan</h2>\n<div class=\"table-scroll\"><table>\n  <tr><th>Area Sorowako</th><th>Program Utama</th></tr>\n  <tr><td>Site Tambang & Smelter</td><td>POP Minerba, Rigger Heavy Duty, K3 Kelistrikan PLTA</td></tr>\n</table></div>\n<h2 id=\"fasilitas-praktik\">Peralatan, Tooling &amp; Sarana Uji Praktik Lapangan</h2>\n<p>Peserta pelatihan dibekali pengalaman langsung mengoperasikan instrumen dan alat keselamatan berstandar industri bersertifikasi:</p>\n<ul class=\"check-list\">\n  <li>Fatigue Scanner & Slope Stability Radar Guide.</li>\n</ul>\n\n<h2 id=\"sasaran-peserta\">Profil Sasaran Peserta Pelatihan</h2>\n<p>Program in-house dan sertifikasi ini dirancang bagi tenaga profesional perusahaan:</p>\n<ul>\n  <li>Pengawas Tambang Nikel, Operator Alat Berat, dan Teknisi PLTA.</li>\n</ul>\n\n<h2 id=\"metodologi-evaluasi\">Metodologi Evaluasi &amp; Uji Kompetensi Kelulusan</h2>\n<p>Penilaian kelulusan peserta dilakukan secara objektif melalui ujian teori tertulis (Pre-Test &amp; Post-Test) dengan batas kelulusan minimal, observasi langsung pada uji praktik lapangan, serta verifikasi portofolio kerja. Peserta yang dinyatakan kompeten akan memperoleh Sertifikat Resmi Kualifikasi K3.</p>\n\n<h2 id=\"program-terkait\">Navigasi Program Terkait &amp; Lanjutan</h2>\n<p>Perkuat integrasi sistem keselamatan dan produktivitas tim operasional fasilitas Anda melalui program pilihan:</p>\n<p>\n  <a href=\"/kategori-pelatihan/pengawas-operasional-pertama-pop/\">Pelatihan POP Tambang</a>\n</p>"
};
