import { PageContentData } from '@/lib/types';

// Map of dynamic content loaders
const contentLoaders: Record<string, () => Promise<{ content: PageContentData }>> = {
  'home': () => import('./pages/home'),
  'kontak': () => import('./pages/kontak'),
  'jenis-pelatihan': () => import('./pages/jenis-pelatihan'),
  'in-house-training': () => import('./pages/in-house-training'),
  'pelatihan-publik': () => import('./pages/pelatihan-publik'),
  'pelatihan-korporat-customized': () => import('./pages/pelatihan-korporat-customized'),
  'in-house-vs-publik-vs-blended': () => import('./pages/in-house-vs-publik-vs-blended'),
  'industri': () => import('./pages/industri'),
  'manufaktur': () => import('./pages/manufaktur'),
  'konstruksi': () => import('./pages/konstruksi'),
  'pertambangan-migas': () => import('./pages/pertambangan-migas'),
  'kesehatan-rumah-sakit': () => import('./pages/kesehatan-rumah-sakit'),
  'logistik-pergudangan': () => import('./pages/logistik-pergudangan'),
  'perbankan-keuangan': () => import('./pages/perbankan-keuangan'),
  'peran-jabatan': () => import('./pages/peran-jabatan'),
  'hrd-manager': () => import('./pages/hrd-manager'),
  'supervisor-team-leader': () => import('./pages/supervisor-team-leader'),
  'safety-officer-k3': () => import('./pages/safety-officer-k3'),
  'manajer-operasional': () => import('./pages/manajer-operasional'),
  'staff-baru-onboarding': () => import('./pages/staff-baru-onboarding'),
  'kategori-pelatihan': () => import('./pages/kategori-pelatihan'),
  'k3-keselamatan-kerja': () => import('./pages/k3-keselamatan-kerja'),
  'manajemen-sdm': () => import('./pages/manajemen-sdm'),
  'kepemimpinan': () => import('./pages/kepemimpinan'),
  'customer-service-soft-skills': () => import('./pages/customer-service-soft-skills'),
  'keuangan-akuntansi': () => import('./pages/keuangan-akuntansi'),
  'sertifikasi-bnsp': () => import('./pages/sertifikasi-bnsp'),
  'konsultasi-pengembangan-kompetensi': () => import('./pages/konsultasi-pengembangan-kompetensi'),
  'training-needs-analysis': () => import('./pages/training-needs-analysis'),
  'penyusunan-kurikulum-korporat': () => import('./pages/penyusunan-kurikulum-korporat'),
  'competency-mapping': () => import('./pages/competency-mapping'),
  'evaluasi-pasca-training-roi': () => import('./pages/evaluasi-pasca-training-roi'),
  'tentang-kami': () => import('./pages/tentang-kami'),
  'faq': () => import('./pages/faq'),
  'glosarium': () => import('./pages/glosarium'),
  'studi-kasus': () => import('./pages/studi-kasus'),
  'blog': () => import('./pages/blog'),
  'confined-space-entry': () => import('./pages/confined-space-entry'),
  'teknisi-k3-ruang-terbatas': () => import('./pages/teknisi-k3-ruang-terbatas'),
  'rescue-ruang-terbatas': () => import('./pages/rescue-ruang-terbatas'),
  'gas-tester': () => import('./pages/gas-tester'),
  'gas-detector': () => import('./pages/gas-detector'),
  'working-at-height': () => import('./pages/working-at-height'),
  'bekerja-di-ketinggian': () => import('./pages/bekerja-di-ketinggian'),
  'fall-protection': () => import('./pages/fall-protection'),
  'rope-access-dasar': () => import('./pages/rope-access-dasar'),
  'rescue-di-ketinggian': () => import('./pages/rescue-di-ketinggian'),
  'operator-scaffolding': () => import('./pages/operator-scaffolding'),
  'pengawas-scaffolding': () => import('./pages/pengawas-scaffolding'),
  'scaffolding-inspector': () => import('./pages/scaffolding-inspector'),
  'rigger': () => import('./pages/rigger'),
  'signalman': () => import('./pages/signalman'),
  'lifting-supervisor': () => import('./pages/lifting-supervisor'),
  'lifting-operation-safety': () => import('./pages/lifting-operation-safety'),
  'operator-forklift': () => import('./pages/operator-forklift'),
  'operator-reach-truck': () => import('./pages/operator-reach-truck'),
  'operator-pallet-stacker': () => import('./pages/operator-pallet-stacker'),
  'operator-crane': () => import('./pages/operator-crane'),
  'operator-mobile-crane': () => import('./pages/operator-mobile-crane'),
  'operator-overhead-crane': () => import('./pages/operator-overhead-crane'),
  'operator-gantry-crane': () => import('./pages/operator-gantry-crane'),
  'operator-hoist': () => import('./pages/operator-hoist'),
  'operator-excavator': () => import('./pages/operator-excavator'),
  'operator-wheel-loader': () => import('./pages/operator-wheel-loader'),
  'operator-bulldozer': () => import('./pages/operator-bulldozer'),
  'operator-dump-truck': () => import('./pages/operator-dump-truck'),
  'keselamatan-alat-berat': () => import('./pages/keselamatan-alat-berat'),
  'hot-work-safety': () => import('./pages/hot-work-safety'),
  'fire-watch': () => import('./pages/fire-watch'),
  'permit-to-work': () => import('./pages/permit-to-work'),
};

export async function getPageContent(key: string): Promise<PageContentData | null> {
  const loader = contentLoaders[key];
  if (!loader) return null;
  const mod = await loader();
  return mod.content;
}
